name: opal
description: >-
  Tokenization and syntax highlighting support for
  various programming languages and data formats.
version: 0.1.0-wip
repository: https://github.com/dart-community/opal

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  collection: ^1.19.1
  night_raven_insight: ^4.0.0
  path: ^1.9.1
  test: ^1.26.3
